trigger: none

stages:
  - stage: BuildAndTest
    displayName: "Building and testing"
    jobs:
      - job: RunOn
        displayName: "on"
        strategy:
          matrix:
            linux:
              imageName: "ubuntu-latest"
              poolName: "Azure Pipelines"
            windows-msvc-2022:
              imageName: "windows-2022"
              poolName: "Azure Pipelines"
            windows-msvc-2019:
              imageName: "windows-2019"
              poolName: "Azure Pipelines"
        pool:
          name: $(poolName)
          vmImage: $(imageName)
        timeoutInMinutes: 60
        steps:
          - checkout: self
            fetchDepth: 1
            lfs: false
            submodules: true
          - script: dotnet build
            displayName: Build
          - script: dotnet test
            displayName: Test
